spring:
  application:
    name: tensquare-eureka
server:
  port: 6868
eureka:
  client:
    #是否将自己注册到eureka中
    register-with-eureka: false
    #是否从eureka中获取信息
    fetch-registry: false
    service-url:
      defaultZone: http://0.0.0.0:${server.port}/eureka/