server:
  port: 9008
spring:
  application:
    name: tensquare-user #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.194.220.59:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: root
mybatis-plus:
#  typeAliasesPackage: com.tensquare.article.pojo
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.tensquare.user.pojo
  global-config:
    id-type: 1
    db-column-underline: false
    refresh-mapper: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true #配置的缓存的全局开关
      lazyLoadingEnabled: true #延时加载的开关
      multipleResultSetsEnabled: true #开启延时加载，否则按需加载 属性
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql语句
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true